modLoader = "javafml"
loaderVersion = "[41,)"
license = "All rights reserved"
[[mods]]
modId = "debug_utils"
version = "${file.jarVersion}"
displayName = "Test Utility"
credits = "Thanks for this example mod goes to Java"
authors = "Love, Cheese and small house plants"
description = '''
Test Utility
'''
[[dependencies.debug_utils]]
modId = "forge"
mandatory = true
versionRange = "[41.0.94,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.debug_utils]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19, )"
ordering = "NONE"
side = "BOTH"
