# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
archives_base_name=debug_utility
minecraft=1.21.10
version=21.10.0
maven_latest=21.10.0-SNAPSHOT
forge_version=1.21.10-60.0.5
fabric_version=0.135.0+1.21.10
fabric_loader=0.17.3
neo_version=21.10.18-beta
# https://ldtteam.jfrog.io/ui/native/parchmentmc-public/org/parchmentmc/data/parchment-1.21.9/
parchment_minecraft=1.21.9
parchment_mapping=2025.10.05

jupiter=6.0.0
mockito_core=5.20.0
mockito_inline=5.2.0

# https://docs.gradle.org/current/userguide/upgrading_version_8.html#xml_parsing_now_requires_recent_parsers
systemProp.javax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
systemProp.javax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl
systemProp.javax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl

# https://github.com/neoforged/NeoGradle/blob/NG_7.0/README.md
neogradle.subsystems.conventions.ide.enabled=false
neogradle.subsystems.conventions.ide.idea.enabled=false
neogradle.subsystems.conventions.ide.idea.compiler-detection=false
