[versions]
gradle_cf = "3.1"
gradle_neoforge = "7.0.163"

[plugins]
cf = { id = "com.kotori316.plugin.cf", version.ref = "gradle_cf" }
neoforge-gradle = { id = "net.neoforged.gradle.userdev", version.ref = "gradle_neoforge" }
