[versions]
gradle_cf = "4.0"
gradle_forge = "7.0.35"
gradle_neoforge = "7.1.38"
gradle_vanilla = "0.3.2"
gradle_loom = "1.17.19"

[plugins]
cf = { id = "com.kotori316.plugin.cf", version.ref = "gradle_cf" }
forge-gradle = { id = "net.minecraftforge.gradle", version.ref = "gradle_forge" }
neoforge-gradle = { id = "net.neoforged.gradle.userdev", version.ref = "gradle_neoforge" }
spongepowered-vanilla = { id = "org.spongepowered.gradle.vanilla", version.ref = "gradle_vanilla" }
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "gradle_loom" }
