modLoader = "javafml"
loaderVersion = "[1,)"
license = "All Rights Reserved."
[[mods]]
modId = "debug_utils"
version = "${file.jarVersion}"
displayName = "DebugUtils"
credits = "Kotori316"
authors = "Kotori316"
description = ''' '''
[[dependencies.debug_utils]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"
