modLoader = "javafml"
loaderVersion = "[1,)"
license = "All rights reserved"
[[mods]]
modId = "test_utility"
version = "${file.jarVersion}"
displayName = "Test Utility"
credits = "Thanks for this example mod goes to Java"
authors = "Love, Cheese and small house plants"
description = '''
Test Utility
'''
[[dependencies.test_utility]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2, 21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.test_utility]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2, )"
ordering = "NONE"
side = "BOTH"
