modLoader = "javafml"
loaderVersion = "[1,)"
license = "All rights reserved"
[[mods]]
modId = "debug_utils"
version = "${file.jarVersion}"
displayName = "DebugUtils"
credits = "Kotori316"
authors = "Kotori316"
description = ''' '''
[[dependencies.debug_utils]]
modId = "neoforge"
type = "required"
versionRange = "[20.5, 21)"
ordering = "NONE"
side = "BOTH"
