name: Build
on:
  push:
    branches:
      - '1.20.*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{github.event_name != 'push'}}
          gradle-home-cache-cleanup: true
      - run: ./gradlew checkReleaseVersion build

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: ['build']
    if: github.event_name == 'push'
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{secrets.GCP_IDENTITY_PROVIDER}}
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}
      - name: Get credentials
        id: get-secrets
        uses: google-github-actions/get-secretmanager-secrets@v1
        with:
          secrets: |-
            cloudflare_s3_endpoint:kotori316-mods-resources/cloudflare_s3_endpoint
            cloudflare_access_key:kotori316-mods-resources/cloudflare_access_key
            cloudflare_secret_key:kotori316-mods-resources/cloudflare_secret_key
      - name: Release Snapshot
        run: ./gradlew -Dorg.gradle.s3.endpoint="${CLOUDFLARE_S3_ENDPOINT}" publish
        env:
          CLOUDFLARE_S3_ENDPOINT: ${{steps.get-secrets.outputs.cloudflare_s3_endpoint}}
          R2_ACCESS_KEY: ${{steps.get-secrets.outputs.cloudflare_access_key}}
          R2_SECRET_KEY: ${{steps.get-secrets.outputs.cloudflare_secret_key}}
          RELEASE_DEBUG: true
