name: Build
on:
  push:
    branches:
      - '1.20.*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        project:
          - TU
          - DU
    env:
      DISABLE_DU: ${{ matrix.project != 'DU' }}
      DISABLE_TU: ${{ matrix.project != 'TU' }}
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: chmod +x ./gradlew
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{github.event_name != 'push'}}
          gradle-home-cache-cleanup: true
      - run: ./gradlew checkReleaseVersion build --scan

  release-snapshot:
    needs: ['build']
    if: github.event_name == 'push'
    permissions:
      id-token: write
      contents: write
    uses: ./.github/workflows/publish.yaml
    with:
      RELEASE_DEBUG: true
    secrets: inherit
