on:
  workflow_call:
    inputs:
      RELEASE_DEBUG:
        type: boolean
        default: true

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true
          gradle-home-cache-cleanup: true
      - name: Compile
        run: ./gradlew classes
      - name: Check version
        run: ./gradlew checkReleaseVersion
        env:
          RELEASE_DEBUG: ${{ inputs.RELEASE_DEBUG }}
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{secrets.GCP_IDENTITY_PROVIDER}}
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}
      - name: Download Private Key
        run: gcloud storage cp gs://kotori316-resources/secring.gpg "${HOME}/secring.gpg"
      - name: Download JKS
        run: gcloud storage cp gs://kotori316-resources/kotori316_keystore.jks "${HOME}/kotori316_keystore.jks"
      - name: Download Public Key
        run: |
          gcloud storage cp gs://kotori316-resources/pgp_public.pub "${HOME}/pgp_public.pub"
          gpg --import "${HOME}/pgp_public.pub"
      - name: Get credentials
        id: get-secrets
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |-
            key_id:kotori316-mods-resources/signing-key-id
            key_password:kotori316-mods-resources/signing-password
            jar_password:kotori316-mods-resources/jar-sign-key-password
            cloudflare_s3_endpoint:kotori316-mods-resources/cloudflare_s3_endpoint
            cloudflare_access_key:kotori316-mods-resources/cloudflare_access_key
            cloudflare_secret_key:kotori316-mods-resources/cloudflare_secret_key
      - name: Release
        run: >-
          ./gradlew
          -Psigning.secretKeyRingFile="${HOME}/secring.gpg"
          -Psigning.password="${KEY_PASSWORD}"
          -Psigning.keyId="${KEY_ID}"
          -PjarSign.keyLocation="${HOME}/kotori316_keystore.jks"
          -PjarSign.keyAlias="ko316"
          -PjarSign.storePass="${JAR_PASSWORD}"
          -Dorg.gradle.s3.endpoint="${CLOUDFLARE_S3_ENDPOINT}"
          build ${{ !inputs.RELEASE_DEBUG && 'registerVersion' || '' }} publishToMavenLocal publish
        env:
          VERSION_FUNCTION_ENDPOINT: ${{ secrets.GCP_VERSION_FUNCTION_ENDPOINT }}
          SERVICE_ACCOUNT: ${{ secrets.GCP_FUNCTION_EXECUTION_ACCOUNT }}
          CLOUDFLARE_S3_ENDPOINT: ${{steps.get-secrets.outputs.cloudflare_s3_endpoint}}
          R2_ACCESS_KEY: ${{steps.get-secrets.outputs.cloudflare_access_key}}
          R2_SECRET_KEY: ${{steps.get-secrets.outputs.cloudflare_secret_key}}
          KEY_PASSWORD: ${{steps.get-secrets.outputs.key_password}}
          KEY_ID: ${{steps.get-secrets.outputs.key_id}}
          JAR_PASSWORD: ${{steps.get-secrets.outputs.jar_password}}
          RELEASE_DEBUG: ${{ inputs.RELEASE_DEBUG }}
      - name: Upload Local Maven
        if: ${{ !cancelled() && !inputs.RELEASE_DEBUG }}
        uses: actions/upload-artifact@v4
        with:
          name: special-octo-happiness-Maven-${{ github.run_number }}
          retention-days: 1
          path: ~/.m2
